# Generated by Django 5.0.2 on 2024-02-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HardQode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='room',
        ),
    ]
